name: Generate Datas

on:
  schedule: # تشغيل كل 12 ساعة
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # 1. التحقق من المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. إنشاء أنيميشن الثعبان
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: KhalfaouiDriss
          svg_out_path: dist/github-contribution-grid-snake.svg

      # 3. التحقق من وجود المجلد dist
      - name: Verify dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: Directory 'dist' does not exist!"
            exit 1
          fi

      # 4. نشر المجلد إلى GitHub Pages
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
